<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GAuvFG1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GAuvFG1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GAuvFG1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournoi' => ['privates', '.errored..service_locator.GAuvFG1.App\\Entity\\Tournoi', NULL, 'Cannot autowire service ".service_locator.GAuvFG1": it needs an instance of "App\\Entity\\Tournoi" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'tournoi' => 'App\\Entity\\Tournoi',
            'entityManager' => '?',
        ]);
    }
}
