<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SZTuZbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..SZTuZb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..SZTuZb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jeuVideo' => ['privates', '.errored..service_locator..SZTuZb.App\\Entity\\JeuVideo', NULL, 'Cannot autowire service ".service_locator..SZTuZb": it needs an instance of "App\\Entity\\JeuVideo" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'jeuVideo' => 'App\\Entity\\JeuVideo',
            'entityManager' => '?',
        ]);
    }
}
