<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MO7DoShService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MO7DoSh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MO7DoSh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catTournoi' => ['privates', '.errored..service_locator.MO7DoSh.App\\Entity\\CatTournois', NULL, 'Cannot autowire service ".service_locator.MO7DoSh": it needs an instance of "App\\Entity\\CatTournois" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'catTournoi' => 'App\\Entity\\CatTournois',
            'entityManager' => '?',
        ]);
    }
}
