<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatTournoisControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MV7mFwi.App\Controller\CatTournoisController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MV7mFwi.App\\Controller\\CatTournoisController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catTournoi' => ['privates', '.errored..service_locator.MV7mFwi.App\\Entity\\CatTournois', NULL, 'Cannot autowire service ".service_locator.MV7mFwi": it needs an instance of "App\\Entity\\CatTournois" but this type has been excluded in "config/services.yaml".'],
        ], [
            'catTournoi' => 'App\\Entity\\CatTournois',
        ]))->withContext('App\\Controller\\CatTournoisController::show()', $container);
    }
}
