<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenreControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DdvBgQL.App\Controller\GenreController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DdvBgQL.App\\Controller\\GenreController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'genre' => ['privates', '.errored..service_locator.DdvBgQL.App\\Entity\\Genre', NULL, 'Cannot autowire service ".service_locator.DdvBgQL": it needs an instance of "App\\Entity\\Genre" but this type has been excluded in "config/services.yaml".'],
        ], [
            'genre' => 'App\\Entity\\Genre',
        ]))->withContext('App\\Controller\\GenreController::show()', $container);
    }
}
