<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2Z1ymMW.App\Entity\Genre' shared service.
     *
     * @return \App\Entity\Genre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2Z1ymMW": it needs an instance of "App\\Entity\\Genre" but this type has been excluded in "config/services.yaml".');
    }
}
