<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJeuVideoControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AmSbGiJ.App\Controller\JeuVideoController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AmSbGiJ.App\\Controller\\JeuVideoController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jeuVideo' => ['privates', '.errored..service_locator.AmSbGiJ.App\\Entity\\JeuVideo', NULL, 'Cannot autowire service ".service_locator.AmSbGiJ": it needs an instance of "App\\Entity\\JeuVideo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'jeuVideo' => 'App\\Entity\\JeuVideo',
        ]))->withContext('App\\Controller\\JeuVideoController::show()', $container);
    }
}
