<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJeuVideoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C5IeA5E.App\Controller\JeuVideoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C5IeA5E.App\\Controller\\JeuVideoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jeuVideoRepository' => ['privates', 'App\\Repository\\JeuVideoRepository', 'getJeuVideoRepositoryService', true],
        ], [
            'jeuVideoRepository' => 'App\\Repository\\JeuVideoRepository',
        ]))->withContext('App\\Controller\\JeuVideoController::index()', $container);
    }
}
