<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ASbXafo.App\Entity\Marque' shared service.
     *
     * @return \App\Entity\Marque
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ASbXafo": it needs an instance of "App\\Entity\\Marque" but this type has been excluded in "config/services.yaml".');
    }
}
