<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembre3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ij4lOfp.App\Entity\Membre' shared service.
     *
     * @return \App\Entity\Membre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ij4lOfp": it needs an instance of "App\\Entity\\Membre" but this type has been excluded in "config/services.yaml".');
    }
}
