<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2qH5xMD.App\Controller\ParticipantController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2qH5xMD.App\\Controller\\ParticipantController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'participant' => ['privates', '.errored..service_locator.2qH5xMD.App\\Entity\\Participant', NULL, 'Cannot autowire service ".service_locator.2qH5xMD": it needs an instance of "App\\Entity\\Participant" but this type has been excluded in "config/services.yaml".'],
        ], [
            'participant' => 'App\\Entity\\Participant',
        ]))->withContext('App\\Controller\\ParticipantController::show()', $container);
    }
}
