<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2.FrpkM.App\Controller\ParticipantController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2.FrpkM.App\\Controller\\ParticipantController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'participantRepository' => ['privates', 'App\\Repository\\ParticipantRepository', 'getParticipantRepositoryService', true],
        ], [
            'participantRepository' => 'App\\Repository\\ParticipantRepository',
        ]))->withContext('App\\Controller\\ParticipantController::index()', $container);
    }
}
