<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8_6yDAt.App\Controller\ParticipantController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8_6yDAt.App\\Controller\\ParticipantController::edit()'] = ($container->privates['.service_locator.8_6yDAt'] ?? $container->load('get_ServiceLocator_86yDAtService'))->withContext('App\\Controller\\ParticipantController::edit()', $container);
    }
}
