<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlateformeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l.GdiLQ.App\Controller\PlateformeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l.GdiLQ.App\\Controller\\PlateformeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'plateformeRepository' => ['privates', 'App\\Repository\\PlateformeRepository', 'getPlateformeRepositoryService', true],
        ], [
            'plateformeRepository' => 'App\\Repository\\PlateformeRepository',
        ]))->withContext('App\\Controller\\PlateformeController::index()', $container);
    }
}
