<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPegiControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TmPSW2K.App\Controller\PegiController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TmPSW2K.App\\Controller\\PegiController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pegi' => ['privates', '.errored..service_locator.TmPSW2K.App\\Entity\\Pegi', NULL, 'Cannot autowire service ".service_locator.TmPSW2K": it needs an instance of "App\\Entity\\Pegi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pegi' => 'App\\Entity\\Pegi',
        ]))->withContext('App\\Controller\\PegiController::show()', $container);
    }
}
