<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournoiControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JB79v1i.App\Controller\TournoiController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JB79v1i.App\\Controller\\TournoiController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tournoiRepository' => ['privates', 'App\\Repository\\TournoiRepository', 'getTournoiRepositoryService', true],
        ], [
            'entityManager' => '?',
            'tournoiRepository' => 'App\\Repository\\TournoiRepository',
        ]))->withContext('App\\Controller\\TournoiController::new()', $container);
    }
}
