<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournoiControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V8mjAA7.App\Controller\TournoiController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V8mjAA7.App\\Controller\\TournoiController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournoi' => ['privates', '.errored..service_locator.V8mjAA7.App\\Entity\\Tournoi', NULL, 'Cannot autowire service ".service_locator.V8mjAA7": it needs an instance of "App\\Entity\\Tournoi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournoi' => 'App\\Entity\\Tournoi',
        ]))->withContext('App\\Controller\\TournoiController::show()', $container);
    }
}
