<?php

namespace Container6bWe2Mv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournoisSQLStatControllerindexSQLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HxeCK0I.App\Controller\TournoisSQLStatController::indexSQL()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HxeCK0I.App\\Controller\\TournoisSQLStatController::indexSQL()'] = ($container->privates['.service_locator.HxeCK0I'] ?? $container->load('get_ServiceLocator_HxeCK0IService'))->withContext('App\\Controller\\TournoisSQLStatController::indexSQL()', $container);
    }
}
