<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2Z1ymMWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Z1ymMW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2Z1ymMW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'genre' => ['privates', '.errored..service_locator.2Z1ymMW.App\\Entity\\Genre', NULL, 'Cannot autowire service ".service_locator.2Z1ymMW": it needs an instance of "App\\Entity\\Genre" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'genre' => 'App\\Entity\\Genre',
            'entityManager' => '?',
        ]);
    }
}
