<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatTournoisControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MO7DoSh.App\Controller\CatTournoisController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MO7DoSh.App\\Controller\\CatTournoisController::edit()'] = ($container->privates['.service_locator.MO7DoSh'] ?? $container->load('get_ServiceLocator_MO7DoShService'))->withContext('App\\Controller\\CatTournoisController::edit()', $container);
    }
}
