<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatTournoisControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HnLUGE5.App\Controller\CatTournoisController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HnLUGE5.App\\Controller\\CatTournoisController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'catTournoisRepository' => ['privates', 'App\\Repository\\CatTournoisRepository', 'getCatTournoisRepositoryService', true],
        ], [
            'entityManager' => '?',
            'catTournoisRepository' => 'App\\Repository\\CatTournoisRepository',
        ]))->withContext('App\\Controller\\CatTournoisController::new()', $container);
    }
}
