<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeExtension_CsrfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.type_extension.csrf' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php';

        return $container->privates['form.type_extension.csrf'] = new \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension(($container->privates['security.csrf.same_origin_token_manager'] ?? self::getSecurity_Csrf_SameOriginTokenManagerService($container)), true, '_token', NULL, 'validators', ($container->privates['form.server_params'] ?? $container->load('getForm_ServerParamsService')), $container->parameters['form.type_extension.csrf.field_attr'], ['App\\Form\\CatTournoisType' => 'submit', 'App\\Form\\GenreType' => 'submit', 'App\\Form\\JeuVideo1Type' => 'submit', 'App\\Form\\JeuVideoType' => 'submit', 'App\\Form\\MarqueType' => 'submit', 'App\\Form\\MembreType' => 'submit', 'App\\Form\\ParticipantType' => 'submit', 'App\\Form\\PegiType' => 'submit', 'App\\Form\\PlateformeType' => 'submit', 'App\\Form\\ProfileType' => 'submit', 'App\\Form\\RegistrationType' => 'submit', 'App\\Form\\TournoiType' => 'submit']);
    }
}
