<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJeuVideoControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..SZTuZb.App\Controller\JeuVideoController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..SZTuZb.App\\Controller\\JeuVideoController::edit()'] = ($container->privates['.service_locator..SZTuZb'] ?? $container->load('get_ServiceLocator__SZTuZbService'))->withContext('App\\Controller\\JeuVideoController::edit()', $container);
    }
}
