<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginTraceControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.flFDgZz.App\Controller\LoginTraceController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.flFDgZz.App\\Controller\\LoginTraceController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loginTraceRepository' => ['privates', 'App\\Repository\\LoginTraceRepository', 'getLoginTraceRepositoryService', true],
        ], [
            'loginTraceRepository' => 'App\\Repository\\LoginTraceRepository',
        ]))->withContext('App\\Controller\\LoginTraceController::index()', $container);
    }
}
