<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembreControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BLz2EcE.App\Controller\MembreController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BLz2EcE.App\\Controller\\MembreController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'membre' => ['privates', '.errored..service_locator.BLz2EcE.App\\Entity\\Membre', NULL, 'Cannot autowire service ".service_locator.BLz2EcE": it needs an instance of "App\\Entity\\Membre" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'membre' => 'App\\Entity\\Membre',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\MembreController::delete()', $container);
    }
}
