<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarqueControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cLNwoHl.App\Controller\MarqueController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cLNwoHl.App\\Controller\\MarqueController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'marque' => ['privates', '.errored..service_locator.cLNwoHl.App\\Entity\\Marque', NULL, 'Cannot autowire service ".service_locator.cLNwoHl": it needs an instance of "App\\Entity\\Marque" but this type has been excluded in "config/services.yaml".'],
        ], [
            'marque' => 'App\\Entity\\Marque',
        ]))->withContext('App\\Controller\\MarqueController::show()', $container);
    }
}
