<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarqueControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ASbXafo.App\Controller\MarqueController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ASbXafo.App\\Controller\\MarqueController::edit()'] = ($container->privates['.service_locator.ASbXafo'] ?? $container->load('get_ServiceLocator_ASbXafoService'))->withContext('App\\Controller\\MarqueController::edit()', $container);
    }
}
