<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPegiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NhIoVus.App\Entity\Pegi' shared service.
     *
     * @return \App\Entity\Pegi
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NhIoVus": it needs an instance of "App\\Entity\\Pegi" but this type has been excluded in "config/services.yaml".');
    }
}
