<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlateformeControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KETPca..App\Controller\PlateformeController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KETPca..App\\Controller\\PlateformeController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'plateforme' => ['privates', '.errored..service_locator.KETPca..App\\Entity\\Plateforme', NULL, 'Cannot autowire service ".service_locator.KETPca.": it needs an instance of "App\\Entity\\Plateforme" but this type has been excluded in "config/services.yaml".'],
        ], [
            'plateforme' => 'App\\Entity\\Plateforme',
        ]))->withContext('App\\Controller\\PlateformeController::show()', $container);
    }
}
