<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPegiControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xliKWtR.App\Controller\PegiController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xliKWtR.App\\Controller\\PegiController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pegiRepository' => ['privates', 'App\\Repository\\PegiRepository', 'getPegiRepositoryService', true],
        ], [
            'pegiRepository' => 'App\\Repository\\PegiRepository',
        ]))->withContext('App\\Controller\\PegiController::index()', $container);
    }
}
