<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipant2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8_6yDAt.App\Entity\Participant' shared service.
     *
     * @return \App\Entity\Participant
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8_6yDAt": it needs an instance of "App\\Entity\\Participant" but this type has been excluded in "config/services.yaml".');
    }
}
