<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPegiControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NhIoVus.App\Controller\PegiController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NhIoVus.App\\Controller\\PegiController::edit()'] = ($container->privates['.service_locator.NhIoVus'] ?? $container->load('get_ServiceLocator_NhIoVusService'))->withContext('App\\Controller\\PegiController::edit()', $container);
    }
}
