<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlateformeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KETPca..App\Entity\Plateforme' shared service.
     *
     * @return \App\Entity\Plateforme
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KETPca.": it needs an instance of "App\\Entity\\Plateforme" but this type has been excluded in "config/services.yaml".');
    }
}
