<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournoiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GAuvFG1.App\Controller\TournoiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GAuvFG1.App\\Controller\\TournoiController::delete()'] = ($container->privates['.service_locator.GAuvFG1'] ?? $container->load('get_ServiceLocator_GAuvFG1Service'))->withContext('App\\Controller\\TournoiController::delete()', $container);
    }
}
