<?php

namespace ContainerWtfRP1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournoiStatControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f1D6G7y.App\Controller\TournoiStatController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f1D6G7y.App\\Controller\\TournoiStatController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournoiRepository' => ['privates', 'App\\Repository\\TournoiRepository', 'getTournoiRepositoryService', true],
            'categorieRepository' => ['privates', 'App\\Repository\\CatTournoisRepository', 'getCatTournoisRepositoryService', true],
        ], [
            'tournoiRepository' => 'App\\Repository\\TournoiRepository',
            'categorieRepository' => 'App\\Repository\\CatTournoisRepository',
        ]))->withContext('App\\Controller\\TournoiStatController::index()', $container);
    }
}
